<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ujian_model extends CI_Model
{

    public $table = 'tbl_ujian';
    public $id = 'id_ujian';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }


    function daftar($limit, $start = 0, $q = NULL)
    {
        $query = ('SELECT
                    tbl_ujian.id_ujian,
                    tbl_ujian.id_soal,
                    tbl_ujian.id_mahasiswa,
                    tbl_ujian.nilai,
                    tbl_ujian.status,
                    tbl_mahasiswa.id_mahasiswa,
                    tbl_mahasiswa.username,
                    tbl_mahasiswa.password,
                    tbl_mahasiswa.nama_mahasiswa,
                    tbl_mahasiswa.asal_sekolah,
                    tbl_mahasiswa.no_pendaftaran,
                    tbl_mahasiswa.gambar
                    FROM
                    tbl_ujian
                    INNER JOIN tbl_mahasiswa ON tbl_mahasiswa.id_mahasiswa = tbl_ujian.id_mahasiswa;
                    ');
        return $this->db->query($query);
    }


    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ujian', $q);
	$this->db->or_like('id_soal', $q);
	$this->db->or_like('id_mahasiswa', $q);
	$this->db->or_like('nilai', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ujian', $q);
	$this->db->or_like('id_soal', $q);
	$this->db->or_like('id_mahasiswa', $q);
	$this->db->or_like('nilai', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ujian_model.php */
/* Location: ./application/models/Ujian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-21 08:07:27 */
/* http://harviacode.com */